# Site settings
title: Rakesh T Sasi
description: 'Software Engineer'
url: '' 
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'Rakesh T Sasi'
  email: t.rakeshsasi@gmail.com
  twitter_username: trakeshsasi
  github_username:  rakeshtsasi
  linkedin_username:  rakesh-t-sasi-a7546a4b

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: pygments

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
